package.json, yarn.lock
=> FEAT: Use latest icons

src/components/iconModal.js, src/pages/index.js
- Anchor modal to bottom when on mobile
- Small style fixes (inner box shadow touch for images, remove unused class and replace with actual class name)
=> Small style tweaks

.babelrc.js, .github/workflows/release.yml, env-config.js, next.config.js, package.json
- Attempt to deploy the app via gh-pages
Some resources I followed:
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
- https://github.com/vercel/next.js/tree/canary/examples/gh-pages
=> Attempt to deploy via gh-pages

.gitignore
- Attempt at fixing https://github.com/lifeomic/chromicons.com/runs/1134678766?check_suite_focus=true
=> GH-Pages: Don't ignore `out` directory

.github/workflows/release.yml
- Provide token for `yarn deploy`?
=> gh-pages: Provide token

package.json, src/pages/index.js, yarn.lock
=> FIX: Use latest chromicons

.github/workflows/deploy.yml, package.json
- Deploy GitHub pages site via GitHub action
=> FEAT: Deploy to GitHub Pages via GitHub action

.eslintrc.js, .github/workflows/pr-branch-build.yml, package.json, src/components/categoryFilters.js, src/components/radio.js, src/pages/index.js
- Use `jsx-a11y`
- Fix errors found by above
- Lint and build on PR branches
=> DEV: Add jsx-a11y ESLint rules + build PRs

src/components/radio.js, src/pages/index.js, src/styles/main.css, tailwind.config.js
- Adjust filters box shadow
- Adjust filters (radio) text size
- Adjust animations
=> DESIGN: Design review feedback

src/pages/index.js
- Add Download All link
- Create shared HeroNavLink component for these links
- Convert nav `<div />` to `<nav />`
- More to come here soon™
=> FEAT: Add Download All link

package.json, yarn.lock
- Upgrade Next.js version 
- https://github.com/vercel/next.js/releases
=> CHORE: Upgrade Next.js version

package.json, scripts/generate-new-icon-metadata.js, src/components/iconModal.js, src/pages/index.js, src/util/metadata.js
- Replace `description` with keywords
- Remove `description` from icon modal
- Update package.json so that `yarn start` runs a "traditional" start, rather than Next's version of start
=> Replace description with keywords, update package.json, remove description from modal

src/pages/_document.js, src/pages/index.js, src/styles/main.css
=> Flex icon container height

src/pages/index.js
I noticed site wasn't responsive on mobile
[https://stackoverflow.com/questions/54898661/tailwind-css-site-not-showing-responsive-version](https://stackoverflow.com/questions/54898661/tailwind-css-site-not-showing-responsive-version)
BEFORE | AFTER
-- | --
=> Make app responsive

src/pages/index.js
-  kebab-case icon names
- Allow search to use raw name as well
=> FEAT: kebab-case icon names+update search

src/pages/index.js
=> BUG: Re-add keywords

package.json, postcss.config.js, src/components/iconModal.js, src/components/radio.js, src/components/searchField.js, src/components/tile.js, src/pages/index.js, src/styles/main.css, tailwind.config.js, yarn.lock
- Upgrade next
- Upgrade tailwind
- Fix breaking changes with new tailwind version
- The gray palette changed a bit between versions, so I tried to make it as close as possible
- Removed CSS in favor of tailwind arbitrary values (https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support)
=> DEPS: Upgrade dependencies for tailwind+next

package.json, src/util/metadata.js, yarn.lock
- Add new icons from Chromicons package
=> FEAT: Use latest chromicons

src/components/radio.js, src/components/tile.js, src/pages/index.js
=> Bump up contrast on all colors failing a11y checks

package.json, src/util/metadata.js, yarn.lock
=> feat: Add `gauge` and `gauge-2`

package.json, src/util/metadata.js, yarn.lock
feat: Add keywords for `broccoli` and `heart-hand`
feat: Bump Chromicons
=> Add keywords for new icons and bump Chromicons

package.json, src/util/metadata.js, yarn.lock
- Bump Chromicons to add: `kidney`, `liver` and `prostate` icons
- Add keywords for new icons
=> Bump chromicons v3.2.0

package.json, src/util/metadata.js, yarn.lock
=> Bump chromicons v3.4.0

package.json, src/util/metadata.js, yarn.lock
=> Bump Chromicons to v3.5.0

package.json, src/util/metadata.js, yarn.lock
=> Bump Chromicons to v3.6.0 

package.json, src/util/metadata.js, yarn.lock
=> Bump Chromicons to v3.7.0

package.json, src/util/metadata.js, yarn.lock
=> Bump chromicons v3.8.0

package.json, src/util/metadata.js, yarn.lock
=> Bump chromicons v3.9.0

package.json, src/util/metadata.js, yarn.lock
=> Bump chromicons v3.10.0

package.json, src/util/metadata.js, yarn.lock
=> Bump Chromicons v3.11.0
